import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const nodePath = process.execPath;
const serverPath = path.join(repoRoot, 'src', 'server.js');
const vbsPath = path.join(repoRoot, 'scripts', 'run-hidden.generated.vbs');
const wscript = path.join(process.env.SystemRoot || 'C:\\Windows', 'System32', 'wscript.exe');

// Write a tiny VBScript launcher that runs node windowless (window style 0 = hidden,
// False = don't wait). "" inside a VBS string literal is one escaped double-quote, so the
// launched command resolves to: "<nodePath>" "<serverPath>".
function generateLauncher() {
  const vbs = [
    "' Auto-generated by schedule-install.js — launches the local-pm daemon with no console window.",
    'Set sh = CreateObject("WScript.Shell")',
    `sh.Run """${nodePath}"" ""${serverPath}""", 0, False`,
    '',
  ].join('\r\n');
  fs.writeFileSync(vbsPath, vbs);
}

generateLauncher();

// Delete any existing task first so install is idempotent (delete-then-create).
// Swallow the failure when the task doesn't exist yet (first install).
try {
  execFileSync('schtasks', ['/delete', '/tn', 'local-pm', '/f'], { stdio: 'pipe' });
} catch {
  // task not registered yet — nothing to delete
}

execFileSync(
  'schtasks',
  [
    '/create',
    '/tn',
    'local-pm',
    '/tr',
    `"${wscript}" "${vbsPath}"`,
    '/sc',
    'onlogon',
    '/rl',
    'limited',
    '/f',
  ],
  { stdio: 'inherit' }
);

console.log("Task 'local-pm' installed. It will run automatically at next log-on,");
console.log('in the background with no console window (windowless via a hidden launcher).');
console.log('Token is stored in token.local — start the server once first if you haven\'t already.');
